### PR TITLE
Improve IP range regex and field descriptions

### PR DESCRIPTION
**Pull request by marchelleboid**
* Regarding the error when entering a block like `/16` or `/20`, it was an issue with the regex
* I updated the descriptions to suggest ranges that actually work and mentioned that the ranges should not overlap
* Regarding parsing and rejecting "bad" ranges ourselves, I don't think there's much value added in doing that since the errors returned are understandable.
* To test "named ranges", go to your VPC network -> Click on the subnet -> "Edit" -> "Add IP range" and add the secondary ranges you want to use for pods and services. Then use the names of those new ranges in the plugin fields.
* I tested putting in invalid ranges (see https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing_secondary_range_pods), like `/8` and `/22`, or having the pod and service ranges overlap. The errors seemed fine to me.

[sc-92162]

### CODE REVIEW

**Review by amandineslx — CHANGES_REQUESTED** [review]
### Versions
* reproduced with plugin version 1.3.0
* validated with plugin built from the PR (revision `966fb5f3344677df424f9a60483ec894f1efa6da`)

### Results
* the error when the IP ranges overlap is not very explicit

### Tested
* deploy DSS with FM in GCP
* upload new plugin version built from the PR (revision `966fb5f3344677df424f9a60483ec894f1efa6da`)
* try to create cluster with pod IP range **/16**
  * see clear error message :white_check_mark:
* try to create cluster with service IP range **/16**
  * see clear error message :white_check_mark:
* try to create cluster with pod IP range **10.0.0.0/16**
  * see error message :x:
```
Failed to start cluster : <class 'subprocess.CalledProcessError'> : 1
```
* in Google Cloud Console, open the subnet
  * edit the subnet
  * add a new IP range **asouilleux-range** **10.1.0.0/21**
  * add a new IP range **asouilleux-range2** **10.2.0.0/21**
* create a cluster with pod IP range **asouilleux-range** and service IP range **asouilleux-range2**
  * created successfully :white_check_mark:

**Comment by marchelleboid** [comment]
> ### Results
> * the error when the IP ranges overlap is not very explicit
> 
> ### Tested
> * try to create cluster with pod IP range **10.0.0.0/16**
>   
>   * see error message ❌
> 
> ```
> Failed to start cluster : <class 'subprocess.CalledProcessError'> : 1
> ```

I just retested on my end, this error becomes clearer when you also have the changes in #26. Here's an example:
```
Failed to start cluster : <type 'exceptions.Exception'> : Fetching cluster endpoint and auth data. WARNING: cluster badIpRange is not RUNNING. The kubernetes API may or may not be available. Check the cluster status for more information. ERROR: (gcloud.container.clusters.get-credentials) cluster badIpRange is missing endpoint. Is it still PROVISIONING?
```

While it still does not mention the exact cause of the cluster being unreachalbe, it does suggest to check the cluster status. (If you do check the GKE UI, you then see the status and the real error about the CIDR not being available). To me, that was enough, rather than trying to parse either the IP range input or the output error message and then guessing what was wrong.

In any case, maybe we can re-review this PR once #26 is merged?

**Comment by amandineslx** [comment]
> In any case, maybe we can re-review this PR once #26 is merged?

OK for me!

**Review by thtrunck — APPROVED** [review]
LGTM. I had never noticed that just using mask was broken (I also never would have though this could work).
It looks like without info the default size are /14 and /20 but the exact block is random so I'm fine with the examples.
We could argue that the message is a bit long especially for something that only people who knows about what they are doing are supposed to use this field but I don't have a better idea and the important part is that it's starting with optional and that the example now works.
Finally I wanted to use weird range name to break the regex but google only allows lowercase letters, numbers and hyphens so we are good here.

**Review by amandineslx — APPROVED** [review]
OK for me, I tested both PR#26 and PR#27 code together

**Pull request merged**
