### PR TITLE
The connectivity test macro in K8s plugin shouldn't try to resolve ip

### PR DESCRIPTION
**Pull request by thtrunck**
[ch47077]
The connectivity test macro try to resolve hostname before checking connectivity.
When the "host" is already an IP this messes up the check.

### CODE REVIEW

**Comment by thtrunck** [comment]
Note that I did the same change in all three plugins (AKS, EKS, GKE):
- https://github.com/dataiku/dss-plugin-aks-clusters/pull/13
- https://github.com/dataiku/dss-plugin-gke-clusters/pull/6
- https://github.com/dataiku/dss-plugin-eks-clusters/pull/8

**Comment by hrjn** [comment]
Looking good with the exception of a small detail: is it expected that the (successful) output of `nc` is displayed in the "Error" block and not the "Output" one?

**Review by hrjn — CHANGES_REQUESTED** [review]
A few remarks:
- is it expected that the (successful) output of `nc` is displayed in the "Error" block and not the "Output" one? 
- can you bump the plugin version in `plugin.json` and `Makefile` to 1.1.1?
- can you document the changes in `README.md` for the new version?

**Comment by thtrunck** [comment]
I made the change to `plugin.json`, `makefile` and `README.md`.
Regarding the output of `nc` it's the default behaviour to have all the debugging (including the connection succeeded) printed on stderr.
I changed the interface to not display stdout (since that's not useful) and I renamed error with Debug (stderr) to make things clearer

**Pull request merged**
